services:
  - type: web
    name: goat-bot
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install --omit=dev
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
